wrapped ursa_cl_credential_public_key_from_json
hyperledger/ursa-wrapper-go pull request #12
Opened 2020-10-22 17:00 UTC by mikaelaTar

Signed-off-by: Mikaela <mikaela@scoir.com>

Summary:
Wrapped `ursa_cl_credential_public_key_from_json`.

2020-10-22 17:04 UTC, m00sey approved these changes

2020-10-22 17:07 UTC, pfeairheller requested changes

2020-10-22 17:07 UTC, pfeairheller commented on pkg/libursa/ursa/ursa_test.go
>  }
You need to add a positive test case here to prove that with a valid JSON, it will work.

2020-10-26 14:36 UTC, pfeairheller approved these changes

2020-10-26 15:02 UTC, merged