wrapped ursa_cl_credential_private_key_from_json
hyperledger/ursa-wrapper-go pull request #13
Opened 2020-10-22 17:00 UTC by mikaelaTar

Signed-off-by: Mikaela <mikaela@scoir.com>

Summary:

Wrapped `ursa_cl_credential_private_key_from_json`.

2020-10-22 17:04 UTC, m00sey approved these changes

2020-10-22 17:08 UTC, pfeairheller requested changes

2020-10-22 17:08 UTC, pfeairheller commented on pkg/libursa/ursa/ursa_test.go
> +	})
You should have a positive test case here.

2020-10-26 14:35 UTC, pfeairheller approved these changes

2020-10-26 14:54 UTC, merged