Initial repo work
hyperledger/ursa-wrapper-go pull request #3
Opened 2020-09-21 00:14 UTC by mikaelaTar

Initial setup including github docs, readme, and header file.

2020-09-21 01:05 UTC, m00sey approved these changes

2020-09-21 19:04 UTC, brentzundel approved these changes

2020-09-21 19:04 UTC, brentzundel commented on .github/CONTRIBUTING.md
> +The contents of this file are heavily "borrowed" from  aries-framework-go, mainly because it is are good.
```suggestion
The contents of this file are heavily "borrowed" from  aries-framework-go, mainly because it is good.
```

2020-09-21 21:29 UTC, ryjones commented
Hi - please rebase and squash, thanks.

2020-09-21 21:31 UTC, ryjones requested changes
Hi - I think you can skip the changes to two files. Please, also squash

2020-09-21 21:31 UTC, ryjones commented on CODEOWNERS
> +*                   @hyperledger/ursa-maintainers @pfeairheller @m00sey @mikaelaTar
pick up the changes on main - don't need these edits

2020-09-21 21:31 UTC, ryjones commented on .github/settings.yml
> +#
I don't see changes - probably don't need to check this in?

2020-09-21 21:37 UTC, ryjones approved these changes

2020-09-22 03:26 UTC, m00sey approved these changes

2020-09-22 03:49 UTC, merged